CREATE TABLE IF NOT EXISTS FavoriteAccounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bank_account VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Payee (
    id INT AUTO_INCREMENT PRIMARY KEY,
    payee_user_id VARCHAR(255) NOT NULL,
    payee_name VARCHAR(255) NOT NULL,
    payee_pass VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BankAccounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bank_code int,
    bank_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)