CREATE TABLE IF NOT EXISTS FavoriteAccounts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bank_account VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	constraint favAccount_pk_fk FOREIGN KEY (id) REFERENCES Payee(ID)
);

CREATE TABLE IF NOT EXISTS Payee (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    payee_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    pass VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BankAccounts (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bank_code int,
    bank_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);